#!/bin/bash

day=$1

while [[ true ]]; do
    if [[ $day =~ ^[0-9]+$ ]]; then
        if [[ $day -gt 0 && $day -lt 26 ]]; then
            break
        fi
    fi
    read -p "Which day should be run? (e.g 5) " day
done

cd Day\ $day/Day-$day/src
cargo run --release --bin Day-$day
